---
title: "Predicting TB Medication Adherence Using a Risk Score Model"
date: "February 2024"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#devtools::install_github("hjeglinton/riskscores", build_vignettes = TRUE)


library(glmnet)
library(pROC)
library(caret)
library(riskscores)
library(probably)
library(gridExtra)
library(gt)
library(gtsummary)
set.seed(1)

```

# Data Preprocessing 



```{r}

raw_data <- read.csv("../../data/tb/Peru_TB_data.csv") 

```





```{r, warning = FALSE}
setwd("../../R")
source('preprocessing.R')
tb_df <- tb_preprocessing(raw_data) 
tb_mat <- tb_as_matrix(tb_df)

```

```{r, eval=FALSE}

tb_df[] <- lapply(tb_df, function(x){return(as.factor(x))})

adherence_summary <- tbl_summary(tb_df, by = "adherence_outcome",
            include = c("gender", "age_cat", "concomitant_tb", "lives_w_mom",
                        "lives_w_parents", "current_sx_none", "pills", "dosis_fijas",
                        "monoR", "adr_freq", "fam_accompany_dot", "fam_dislikefriends",
                        "autonomy_obedient", "self_eff_cat", "phq9_tot_cat",
                        "audit_cat", "tobacco_freq", "drug_use", "ace_cat",
                        "stig_health_ctr", "stig_tot_cat", "tto_anterior_tb",
                        "prior_covid", "covid_es", "monitor1", "psych_intervention",
                        "family_median", "health_svc_median", "motiv_median",
                        "knowledge_median"),
            type = list(concomitant_tb ~ "categorical",
                        lives_w_mom ~ "categorical",
                        dosis_fijas ~ "categorical",
                        monoR ~ "categorical",
                        drug_use ~ "categorical"),
            label = list(
              gender = "Gender",
              concomitant_tb = "Concomitant TB",
              lives_w_mom = "Lives with mom", 
              lives_w_parents = "Lives with parents",
              current_sx_none = "No current symptoms",
              pills = "Pills",
              dosis_fijas = "Fixed doses",
              monoR = "Isoniazid monoresistance",
              adr_freq = "Frequency of adverse reactions",
              fam_accompany_dot = "Accompanied by family",
              fam_dislikefriends = "Family dislikes friends",
              autonomy_obedient = "Obedient autonomy",
              tobacco_freq = "Tobacco use",
              drug_use = "Drug use frequency",
              stig_health_ctr = "Health center stigma",
              tto_anterior_tb = "Prior TB treatment",
              prior_covid = "Prior COVID",
              covid_es = "COVID concerns",
              monitor1 = "Treatment administration",
              psych_intervention = "Psychological intervention",
              family_median = "Family support",
              health_svc_median = "Health services",
              motiv_median = "Motivation",
              knowledge_median = "TB knowledge",
              age_cat = "Age",
              audit_cat = "Alcohol use",
              ace_cat = "Adverse childhood experiences",
              self_eff_cat = "Self-efficacy",
              stig_tot_cat = "Total stigma",
              phq9_tot_cat = "Depression"
              
            )) %>%
  add_p() %>%
  as_gt() %>%
  gt::as_latex() %>%
  as.character() %>%
  write_lines(file = "adherence_tab.tex")


```


```{r, out.width="75%", fig.align = 'center', warning = FALSE}
X <- as.matrix(tb_mat[,-ncol(tb_mat)])
y <- tb_mat[,ncol(tb_mat)]

```


```{r, out.width="75%", fig.align = 'center', warning = FALSE}
# CV
# get folds
folds <- stratify_folds(y, nfolds = 5, seed = 1)

# Lasso 
lasso_res <- cv.glmnet(x=X[,-1], y=y, alpha=1, foldid = folds)
lasso_mod <- glmnet(x=X[,-1], y=y, lambda=lasso_res$lambda.min, alpha=1, foldid = folds)
coef_lasso <- coef(lasso_mod)

# Rounded Lasso
nonzero_lasso <- coef_lasso[coef_lasso != 0][-1]
      
scalar <- max(abs(nonzero_lasso))/10
b0_lasso_scaled <- coef_lasso[1]/scalar
coef_lasso_rounded <- c(b0_lasso_scaled, 
                        round(coef_lasso[-1]/scalar, 0))
rlasso_scores <- as.vector(X[,-1] %*% coef_lasso_rounded[-1])
rlasso_mod <- glm(y ~ rlasso_scores, family = "binomial")

# RISKCD CV
cv_results <- cv_risk_mod(X, y, foldids = folds, a = -10, b = 10, nlambda = 25, beta = as.vector(coef_lasso), seed = 1)

plot(cv_results, lambda_text = FALSE) + 
  labs(title = "Figure 1. Cross Validation Results")

# RISKCD
mod_cd <- risk_mod(X, y, lambda0 = cv_results$lambda_min, a = -10, b = 10, seed = 1, beta = as.vector(coef_lasso))
coef_cd <- coef(mod_cd)

```



```{r}

# Compare coefficients

data.frame(lasso = round(as.vector(coef_lasso),3),
           r_lasso = as.vector(coef_lasso_rounded), 
           cd = coef_cd) %>%
  slice(-1) %>%
  filter_all(any_vars(.!=0))
  


```

```{r}
# Compare AUC 

cd_probs <- predict(mod_cd, type = "response")[,1]
lasso_probs <- as.vector(predict(lasso_mod, newx=X[,-1]))
rlasso_probs <- predict(rlasso_mod, type = "response")

cd_roc <- roc(y, cd_probs, quiet = TRUE)
lasso_roc <- roc(y, lasso_probs, quiet = TRUE)
round_roc <- roc(y, rlasso_probs, quiet = TRUE) 

cd_roc$auc
cd_roc %>% ci.auc()

lasso_roc$auc
lasso_roc %>% ci.auc

round_roc$auc
round_roc %>% ci.auc

# Brier score
cd_brier <- mean((cd_probs - y)^2) # 0.1219
lasso_brier <- mean((lasso_probs - y)^2) # 0.1352
round_brier <- mean((rlasso_probs - y)^2) # 0.1293
```







```{r}




# Calibration plot
cal_data <- data.frame(y, X[,-1], riskcd = cd_probs, rlasso = rlasso_probs, lasso = lasso_probs) #%>%
  #pivot_longer(cols = c("riskcd", "rlasso"), values_to = "pred", names_to = "model")


cal_plot_riskcd <- cal_data %>%
  cal_plot_logistic(y, riskcd) + labs(x = "Observed Risk", y = "", title = "RiskCD")

cal_plot_rlasso <- cal_data %>%
  cal_plot_logistic(y, rlasso) + labs(x = "Observed Risk", y = "Estimated Risk", title = "Rounded Lasso")

cal_plot_grid <- grid.arrange( cal_plot_rlasso, cal_plot_riskcd, ncol = 2)

ggsave(cal_plot_grid, width = 7, height = 5, dpi = 300, filename = "adherence_cal.png")


```



```{r}
# Compare objective functions

riskscores:::obj_fcn(X, y, gamma = 1, beta = coef_lasso_rounded, weights = rep(1, nrow(X)), lambda0 = cv_results$lambda_min)

riskscores:::obj_fcn(X, y, gamma = mod_cd$gamma, beta = mod_cd$beta, weights = rep(1, nrow(X)), lambda0 = cv_results$lambda_min)


```

```{r}
# Match scores to risk 

data.frame(score = seq(-1, 12)) %>%
  mutate(risk = round(get_risk(mod_cd, score),3)) %>%
  t()
```

